package k2;

/* renamed from: k2.m  reason: case insensitive filesystem */
public abstract class C1156m {

    /* renamed from: a  reason: collision with root package name */
    public static final C1145b f13021a = new C1145b(2, "MULTI_PROCESS", "MULTI_PROCESS_QUERY");

    /* renamed from: b  reason: collision with root package name */
    public static final C1145b f13022b = new C1145b(6, "FORCE_DARK", "FORCE_DARK");

    static {
        new C1145b(0, "VISUAL_STATE_CALLBACK", "VISUAL_STATE_CALLBACK");
        new C1145b(0, "OFF_SCREEN_PRERASTER", "OFF_SCREEN_PRERASTER");
        new C1145b(3, "SAFE_BROWSING_ENABLE", "SAFE_BROWSING_ENABLE");
        new C1145b(1, "DISABLED_ACTION_MODE_MENU_ITEMS", "DISABLED_ACTION_MODE_MENU_ITEMS");
        new C1145b(4, "START_SAFE_BROWSING", "START_SAFE_BROWSING");
        new C1145b(4, "SAFE_BROWSING_WHITELIST", "SAFE_BROWSING_WHITELIST");
        new C1145b(4, "SAFE_BROWSING_WHITELIST", "SAFE_BROWSING_ALLOWLIST");
        new C1145b(4, "SAFE_BROWSING_ALLOWLIST", "SAFE_BROWSING_WHITELIST");
        new C1145b(4, "SAFE_BROWSING_ALLOWLIST", "SAFE_BROWSING_ALLOWLIST");
        new C1145b(4, "SAFE_BROWSING_PRIVACY_POLICY_URL", "SAFE_BROWSING_PRIVACY_POLICY_URL");
        new C1145b(1, "SERVICE_WORKER_BASIC_USAGE", "SERVICE_WORKER_BASIC_USAGE");
        new C1145b(1, "SERVICE_WORKER_CACHE_MODE", "SERVICE_WORKER_CACHE_MODE");
        new C1145b(1, "SERVICE_WORKER_CONTENT_ACCESS", "SERVICE_WORKER_CONTENT_ACCESS");
        new C1145b(1, "SERVICE_WORKER_FILE_ACCESS", "SERVICE_WORKER_FILE_ACCESS");
        new C1145b(1, "SERVICE_WORKER_BLOCK_NETWORK_LOADS", "SERVICE_WORKER_BLOCK_NETWORK_LOADS");
        new C1145b(1, "SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST", "SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST");
        new C1145b(0, "RECEIVE_WEB_RESOURCE_ERROR", "RECEIVE_WEB_RESOURCE_ERROR");
        new C1145b(0, "RECEIVE_HTTP_ERROR", "RECEIVE_HTTP_ERROR");
        new C1145b(1, "SHOULD_OVERRIDE_WITH_REDIRECTS", "SHOULD_OVERRIDE_WITH_REDIRECTS");
        new C1145b(4, "SAFE_BROWSING_HIT", "SAFE_BROWSING_HIT");
        new C1145b(1, "WEB_RESOURCE_REQUEST_IS_REDIRECT", "WEB_RESOURCE_REQUEST_IS_REDIRECT");
        new C1145b(0, "WEB_RESOURCE_ERROR_GET_DESCRIPTION", "WEB_RESOURCE_ERROR_GET_DESCRIPTION");
        new C1145b(0, "WEB_RESOURCE_ERROR_GET_CODE", "WEB_RESOURCE_ERROR_GET_CODE");
        new C1145b(4, "SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY", "SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY");
        new C1145b(4, "SAFE_BROWSING_RESPONSE_PROCEED", "SAFE_BROWSING_RESPONSE_PROCEED");
        new C1145b(4, "SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL", "SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL");
        new C1145b(0, "WEB_MESSAGE_PORT_POST_MESSAGE", "WEB_MESSAGE_PORT_POST_MESSAGE");
        new C1145b(0, "WEB_MESSAGE_PORT_CLOSE", "WEB_MESSAGE_PORT_CLOSE");
        new C1145b(2, "WEB_MESSAGE_ARRAY_BUFFER", "WEB_MESSAGE_ARRAY_BUFFER");
        new C1145b(0, "WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK", "WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK");
        new C1145b(0, "CREATE_WEB_MESSAGE_CHANNEL", "CREATE_WEB_MESSAGE_CHANNEL");
        new C1145b(0, "POST_WEB_MESSAGE", "POST_WEB_MESSAGE");
        new C1145b(0, "WEB_MESSAGE_CALLBACK_ON_MESSAGE", "WEB_MESSAGE_CALLBACK_ON_MESSAGE");
        new C1145b(3, "GET_WEB_VIEW_CLIENT", "GET_WEB_VIEW_CLIENT");
        new C1145b(3, "GET_WEB_CHROME_CLIENT", "GET_WEB_CHROME_CLIENT");
        new C1145b(6, "GET_WEB_VIEW_RENDERER", "GET_WEB_VIEW_RENDERER");
        new C1145b(6, "WEB_VIEW_RENDERER_TERMINATE", "WEB_VIEW_RENDERER_TERMINATE");
        new C1145b(5, "TRACING_CONTROLLER_BASIC_USAGE", "TRACING_CONTROLLER_BASIC_USAGE");
        new C1153j();
        new C1153j();
        new C1145b(6, "WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE", "WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE");
        new C1154k();
        new C1145b(2, "PROXY_OVERRIDE", "PROXY_OVERRIDE:3");
        new C1145b(2, "FORCE_DARK_STRATEGY", "FORCE_DARK_BEHAVIOR");
        new C1145b(2, "WEB_MESSAGE_LISTENER", "WEB_MESSAGE_LISTENER");
        new C1145b(2, "DOCUMENT_START_SCRIPT", "DOCUMENT_START_SCRIPT:1");
        new C1145b(2, "PROXY_OVERRIDE_REVERSE_BYPASS", "PROXY_OVERRIDE_REVERSE_BYPASS");
        new C1145b(2, "GET_VARIATIONS_HEADER", "GET_VARIATIONS_HEADER");
        new C1145b(2, "ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY", "ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY");
        new C1145b(2, "GET_COOKIE_INFO", "GET_COOKIE_INFO");
        new C1145b(2, "REQUESTED_WITH_HEADER_ALLOW_LIST", "REQUESTED_WITH_HEADER_ALLOW_LIST");
        new C1145b(2, "USER_AGENT_METADATA", "USER_AGENT_METADATA");
        new C1145b(2, "MULTI_PROFILE", "MULTI_PROFILE");
        new C1145b(2, "ATTRIBUTION_REGISTRATION_BEHAVIOR", "ATTRIBUTION_BEHAVIOR");
    }
}
